### ISSUE TITLE
Incompatible with graphql-upload@10

### ISSUE THREAD

**Issue by bostrom** [mattbretl/postgraphile-plugin-upload-field#9]
graphql-upload ships with an implementation of the GraphQLUpload class, which also is defined here https://github.com/graphile-contrib/postgraphile-plugin-upload-field/blob/master/src/UploadFieldPlugin.js#L19. Version 10 of graphql-upload changes the implementation, so the almost-identical implementation of postgraphile-plugin-upload-field breaks it.

**Comment by mattbretl** [comment]
Fixed in 1.0.0-alpha.10.
